export const userHelper = {
  data: [
    {
      id: "users/1",
      userId: 1,
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      phoneNumber: "1234567890",
      gender: "Male",
      department: "Engineering",
      role: "Admin",
      country: "USA",
      isActive: true,
      createdAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "users/2",
      userId: 2,
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@example.com",
      phoneNumber: "0987654321",
      gender: "Female",
      department: "Marketing",
      role: "User",
      country: "UK",
      isActive: false,
      createdAt: "2024-02-20T08:00:00Z",
    },
    {
      id: "users/3",
      userId: 3,
      firstName: "Alice",
      lastName: "Johnson",
      email: "alice.j@example.com",
      phoneNumber: "5551234567",
      gender: "Female",
      department: "Engineering",
      role: "Manager",
      country: "India",
      isActive: true,
      createdAt: "2024-03-05T14:45:00Z",
    },
    {
      id: "users/4",
      userId: 4,
      firstName: "Bob",
      lastName: "Williams",
      email: "bob.williams@example.com",
      phoneNumber: "5559876543",
      gender: "Male",
      department: "Sales",
      role: "User",
      country: "Canada",
      isActive: true,
      createdAt: "2024-03-10T09:15:00Z",
    },
    {
      id: "users/5",
      userId: 5,
      firstName: "Carol",
      lastName: "Brown",
      email: "carol.brown@example.com",
      phoneNumber: "5554443322",
      gender: "Female",
      department: "HR",
      role: "Viewer",
      country: "Australia",
      isActive: false,
      createdAt: "2024-03-18T11:00:00Z",
    },
    {
      id: "users/6",
      userId: 6,
      firstName: "David",
      lastName: "Jones",
      email: "david.jones@example.com",
      phoneNumber: "5551112233",
      gender: "Male",
      department: "Finance",
      role: "Manager",
      country: "USA",
      isActive: true,
      createdAt: "2024-04-01T07:30:00Z",
    },
    {
      id: "users/7",
      userId: 7,
      firstName: "Eva",
      lastName: "Garcia",
      email: "eva.garcia@example.com",
      phoneNumber: "5558889900",
      gender: "Female",
      department: "Engineering",
      role: "User",
      country: "UK",
      isActive: true,
      createdAt: "2024-04-05T13:20:00Z",
    },
    {
      id: "users/8",
      userId: 8,
      firstName: "Frank",
      lastName: "Martinez",
      email: "frank.m@example.com",
      phoneNumber: "5556667788",
      gender: "Male",
      department: "Marketing",
      role: "Admin",
      country: "India",
      isActive: false,
      createdAt: "2024-04-12T16:00:00Z",
    },
    {
      id: "users/9",
      userId: 9,
      firstName: "Grace",
      lastName: "Lee",
      email: "grace.lee@example.com",
      phoneNumber: "5553334455",
      gender: "Female",
      department: "Sales",
      role: "Viewer",
      country: "Canada",
      isActive: true,
      createdAt: "2024-04-20T10:45:00Z",
    },
    {
      id: "users/10",
      userId: 10,
      firstName: "Henry",
      lastName: "Wilson",
      email: "henry.w@example.com",
      phoneNumber: "5552221100",
      gender: "Male",
      department: "HR",
      role: "User",
      country: "Australia",
      isActive: true,
      createdAt: "2024-04-25T08:30:00Z",
    },
    {
      id: "users/11",
      userId: 11,
      firstName: "Isla",
      lastName: "Anderson",
      email: "isla.a@example.com",
      phoneNumber: "5557778899",
      gender: "Female",
      department: "Finance",
      role: "Manager",
      country: "USA",
      isActive: false,
      createdAt: "2024-05-01T12:00:00Z",
    },
    {
      id: "users/12",
      userId: 12,
      firstName: "Jack",
      lastName: "Thomas",
      email: "jack.thomas@example.com",
      phoneNumber: "5550001122",
      gender: "Male",
      department: "Engineering",
      role: "Viewer",
      country: "UK",
      isActive: true,
      createdAt: "2024-05-03T09:00:00Z",
    },
    {
      id: "users/13",
      userId: 13,
      firstName: "Karen",
      lastName: "Taylor",
      email: "karen.t@example.com",
      phoneNumber: "5554455667",
      gender: "Other",
      department: "Marketing",
      role: "User",
      country: "India",
      isActive: true,
      createdAt: "2024-05-07T15:30:00Z",
    },
    {
      id: "users/14",
      userId: 14,
      firstName: "Leo",
      lastName: "Moore",
      email: "leo.moore@example.com",
      phoneNumber: "5559990011",
      gender: "Male",
      department: "Sales",
      role: "Manager",
      country: "Canada",
      isActive: false,
      createdAt: "2024-05-10T11:15:00Z",
    },
    {
      id: "users/15",
      userId: 15,
      firstName: "Mia",
      lastName: "Jackson",
      email: "mia.jackson@example.com",
      phoneNumber: "5552345678",
      gender: "Female",
      department: "HR",
      role: "Admin",
      country: "Australia",
      isActive: true,
      createdAt: "2024-05-14T14:00:00Z",
    },
    {
      id: "users/16",
      userId: 16,
      firstName: "Nathan",
      lastName: "White",
      email: "nathan.w@example.com",
      phoneNumber: "5558765432",
      gender: "Male",
      department: "Finance",
      role: "User",
      country: "USA",
      isActive: true,
      createdAt: "2024-05-18T08:45:00Z",
    },
    {
      id: "users/17",
      userId: 17,
      firstName: "Olivia",
      lastName: "Harris",
      email: "olivia.h@example.com",
      phoneNumber: "5551357924",
      gender: "Female",
      department: "Engineering",
      role: "Manager",
      country: "UK",
      isActive: false,
      createdAt: "2024-05-22T10:00:00Z",
    },
    {
      id: "users/18",
      userId: 18,
      firstName: "Paul",
      lastName: "Clark",
      email: "paul.clark@example.com",
      phoneNumber: "5552468013",
      gender: "Other",
      department: "Marketing",
      role: "Viewer",
      country: "India",
      isActive: true,
      createdAt: "2024-06-01T07:00:00Z",
    },
    {
      id: "users/19",
      userId: 19,
      firstName: "Quinn",
      lastName: "Lewis",
      email: "quinn.lewis@example.com",
      phoneNumber: "5553692581",
      gender: "Male",
      department: "Sales",
      role: "User",
      country: "Canada",
      isActive: true,
      createdAt: "2024-06-05T13:30:00Z",
    },
    {
      id: "users/20",
      userId: 20,
      firstName: "Rachel",
      lastName: "Walker",
      email: "rachel.w@example.com",
      phoneNumber: "5557413690",
      gender: "Female",
      department: "HR",
      role: "Manager",
      country: "Australia",
      isActive: false,
      createdAt: "2024-06-10T16:45:00Z",
    },
  ],
  total: 20,
};